# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Antonio Ossa
tagline:          'RecSys blog'
description:      'Recommender Systems blog, by <a href="https://github.com/aaossa" target="_blank">@aaossa</a>'
url:              https://aaossa.github.io/recsys
baseurl:          /recsys

author:
  name:           'Antonio Ossa'
  url:            https://github.com/aaossa
  photo:          https://avatars3.githubusercontent.com/u/10425834?v=3&s=200

paginate:         5

exclude:          ['README.md', 'LICENSE.md', comment.template.md']

# Custom vars
version:          2.1.0
